name: ksanday_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  countries_world_map: ^1.3.0
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  

  assets:
    - images/logo.png
    - images/logo_colored.png
    - assets/data.json
  
  fonts:
    - family: IBMPLEX
      fonts:
        - asset: fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: fonts/IBMPlexSansArabic-Light.ttf
          weight: 200
        - asset: fonts/IBMPlexSansArabic-Bold.ttf
          weight: 600